import csv

data = [
    ("en", "ZenWedge: Focus Timer", "Sensory focus timer with tactile controls, AI chimes, and productivity tracking", "ZenWedge is an elegant, sensory-rich countdown timer designed to help you cultivate deep, distraction-free focus.\n\nFeatures:\n• Tactile Time Adjustment: Slide the mechanical wedge to configure your focus sessions.\n• Therapeutic Chimes: Authentic singing bowls, raindrops, and zen bells.\n• AI Recommendations: Let Gemini analyze your history to recommend the optimal chime.\n• Analytics: Monitor your attention trends with local tracking and charts.\n\nStart focusing today with ZenWedge."),
    ("ar", "ZenWedge: مؤقت التركيز", "مؤقت حسي مع تحكم باللمس، أصوات مريحة، تتبع الإنتاجية وتوصيات الذكاء الاصطناعي.", "ZenWedge هو مؤقت للعد التنازلي غني بالحواس مصمم لمساعدتك على التركيز العميق.\n\nالميزات:\n• تعديل الوقت باللمس: قم بتمرير الوتد لضبط جلسات التركيز.\n• أصوات مريحة: أجراس زن وأصوات المطر.\n• توصيات الذكاء الاصطناعي: دع Gemini يوصي بالصوت الأمثل.\n• الإحصائيات: راقب اتجاهات تركيزك من خلال التتبع المحلي.\n\nابدأ التركيز اليوم مع ZenWedge."),
    ("de", "ZenWedge: Fokus-Timer", "Sensorischer Fokus-Timer mit taktiler Steuerung, KI-Klängen und Statistiken.", "ZenWedge ist ein eleganter Countdown-Timer für tiefe, ablenkungsfreie Konzentration.\n\nFunktionen:\n• Taktile Zeiteinstellung: Schieben Sie den Keil, um Sitzungen zu konfigurieren.\n• Therapeutische Klänge: Authentische Klangschalen und Zen-Glocken.\n• KI-Empfehlungen: Gemini empfiehlt den optimalen Klang.\n• Analysen: Überwachen Sie Ihre Aufmerksamkeitstrends.\n\nBeginnen Sie noch heute mit ZenWedge."),
    ("es", "ZenWedge: Reloj de Enfoque", "Temporizador táctil con sonidos relajantes, inteligencia artificial y datos.", "ZenWedge es un temporizador de cuenta regresiva elegante y sensorial diseñado para la concentración profunda.\n\nCaracterísticas:\n• Ajuste de tiempo táctil: Desliza la cuña para configurar tus sesiones.\n• Sonidos terapéuticos: Cuencos tibetanos y campanas zen.\n• Recomendaciones de IA: Gemini analiza tu historial para sugerir el mejor sonido.\n• Estadísticas: Monitorea tus tendencias de atención.\n\nComienza a enfocarte hoy con ZenWedge."),
    ("fr", "ZenWedge: Minuteur de Focus", "Minuteur sensoriel avec contrôles tactiles, sons d'ambiance et suivi par IA.", "ZenWedge est un minuteur de compte à rebours élégant conçu pour vous aider à cultiver une concentration profonde.\n\nCaractéristiques:\n• Ajustement tactile: Faites glisser pour configurer vos sessions.\n• Sons apaisants: Bols chantants et cloches zen.\n• Recommandations IA: L'IA Gemini vous suggère le son optimal.\n• Analyses: Suivez vos tendances de concentration.\n\nCommencez à vous concentrer avec ZenWedge."),
    ("hi", "ZenWedge: फोकस टाइमर", "स्पर्श नियंत्रण, सुखदायक ध्वनियों और एआई के साथ एक संवेदी फोकस टाइमर।", "ZenWedge एक सुंदर, संवेदी-समृद्ध उलटी गिनती टाइमर है जिसे आपको गहरे फोकस में मदद करने के लिए डिज़ाइन किया गया है।\n\nविशेषताएं:\n• स्पर्श समय समायोजन: अपने सत्रों को कॉन्फ़िगर करने के लिए स्लाइड करें।\n• सुखदायक ध्वनियां: प्रामाणिक गायन कटोरे और ज़ेन घंटी।\n• एआई अनुशंसाएँ: एआई को इष्टतम ध्वनि की सिफारिश करने दें।\n• सांख्यिकी: अपने ध्यान के रुझानों की निगरानी करें।\n\nआज ही ZenWedge के साथ ध्यान केंद्रित करना शुरू करें।"),
    ("id", "ZenWedge: Fokus Timer", "Timer fokus sensorik dengan kontrol sentuh, suara ambient, dan log fokus.", "ZenWedge adalah penghitung waktu mundur yang elegan dan kaya sensorik untuk fokus mendalam.\n\nFitur:\n• Penyesuaian Waktu Taktil: Geser baji untuk mengonfigurasi sesi Anda.\n• Lonceng Terapeutik: Mangkuk bernyanyi otentik dan lonceng zen.\n• Rekomendasi AI: Biarkan Gemini merekomendasikan suara yang optimal.\n• Analitik: Pantau tren perhatian Anda.\n\nMulai fokus hari ini dengan ZenWedge."),
    ("it", "ZenWedge: Timer Focus", "Timer sensoriale con controlli tattili, suoni ambientali e AI per il focus.", "ZenWedge è un elegante timer per il conto alla rovescia progettato per la concentrazione profonda.\n\nCaratteristiche:\n• Regolazione tattile: Scorri per configurare le tue sessioni.\n• Suoni terapeutici: Campane tibetane e suoni zen.\n• Raccomandazioni AI: Lascia che Gemini consigli il suono ottimale.\n• Analisi: Monitora le tue tendenze di attenzione.\n\nInizia a concentrarti oggi con ZenWedge."),
    ("ja", "ZenWedge: 集中タイマー", "触覚コントロール、環境音、AI推奨機能を備えた集中力タイマー。", "ZenWedgeは、深く気を散らさない集中力を養うために設計されたエレガントなカウントダウンタイマーです。\n\n特徴：\n• 触覚的な時間調整：ウェッジをスライドさせてセッションを設定します。\n• セラピーチャイム：本格的なシンギングボウルと禅の鐘。\n• AI推奨：Geminiが最適なサウンドを推奨します。\n• 分析：ローカルトラッキングで注意力の傾向を監視します。\n\n今日からZenWedgeで集中しましょう。"),
    ("ko", "ZenWedge: 집중 타이머", "촉각 제어, 주변 소리 및 AI 기능이 있는 감각적인 집중 타이머.", "ZenWedge는 깊은 집중력을 기르도록 설계된 우아한 카운트다운 타이머입니다.\n\n기능:\n• 촉각 시간 조정: 웨지를 밀어 세션을 구성합니다.\n• 치료 차임벨: 싱잉볼 및 빗소리.\n• AI 추천: Gemini가 최적의 소리를 추천합니다.\n• 분석: 로컬 추적으로 주의력 추세를 모니터링합니다.\n\n오늘 ZenWedge와 함께 집중을 시작하세요."),
    ("nl", "ZenWedge: Focus Timer", "Sensorische focustimer met tactiele bediening, AI-geluiden en statistieken.", "ZenWedge is een elegante countdown-timer die is ontworpen om diepe focus te cultiveren.\n\nKenmerken:\n• Tactiele tijdaanpassing: Verschuif de wig om uw sessies te configureren.\n• Therapeutische klokken: Authentieke klankschalen en zen-bellen.\n• AI-aanbevelingen: Laat Gemini het optimale geluid aanbevelen.\n• Analyse: Bewaak uw aandachtstrends.\n\nBegin vandaag nog met focussen met ZenWedge."),
    ("pl", "ZenWedge: Minutnik", "Sensoryczny minutnik z dotykowym sterowaniem, dźwiękami otoczenia i AI.", "ZenWedge to elegancki minutnik zaprojektowany, aby pomóc Ci w głębokim skupieniu.\n\nCechy:\n• Dotykowa regulacja czasu: Przesuń klin, aby skonfigurować sesję.\n• Dźwięki terapeutyczne: Autentyczne gongi i dzwonki zen.\n• Rekomendacje AI: Niech Gemini poleci optymalny dźwięk.\n• Analizy: Monitoruj swoje trendy skupienia.\n\nZacznij się skupiać już dziś z ZenWedge."),
    ("pt", "ZenWedge: Temporizador", "Temporizador sensorial com controle tátil, sons relaxantes e IA inteligente.", "ZenWedge é um temporizador de contagem regressiva elegante projetado para o foco profundo.\n\nCaracterísticas:\n• Ajuste de tempo tátil: Deslize a cunha para configurar suas sessões.\n• Sons terapêuticos: Taças tibetanas e sinos zen.\n• Recomendações de IA: Deixe o Gemini recomendar o som ideal.\n• Estatísticas: Monitore suas tendências de atenção.\n\nComece a focar hoje com o ZenWedge."),
    ("ru", "ZenWedge: Таймер Фокуса", "Сенсорный таймер фокуса с тактильным управлением, звуками и аналитикой ИИ.", "ZenWedge — это элегантный таймер обратного отсчета для глубокой концентрации.\n\nФункции:\n• Тактильная настройка: Сдвиньте клин, чтобы настроить сеанс.\n• Терапевтические звуки: Тибетские чаши и дзен-колокольчики.\n• Рекомендации ИИ: Gemini порекомендует оптимальный звук.\n• Аналитика: Следите за своими тенденциями внимания.\n\nНачните фокусироваться сегодня с ZenWedge."),
    ("sv", "ZenWedge: Fokus Timer", "Sensorisk fokustimer med taktila kontroller, omgivande ljud och AI.", "ZenWedge är en elegant nedräkningstimer designad för att hjälpa dig fokusera.\n\nFunktioner:\n• Taktil tidsjustering: Skjut för att konfigurera dina sessioner.\n• Terapeutiska ljud: Autentiska klangskålar och zen-klockor.\n• AI-rekommendationer: Låt Gemini rekommendera det optimala ljudet.\n• Analys: Övervaka dina uppmärksamhetstrender.\n\nBörja fokusera idag med ZenWedge."),
    ("th", "ZenWedge: ตัวจับเวลา", "ตัวจับเวลาสมาธิแบบสัมผัสพร้อมเสียงบรรยากาศและระบบ AI อัจฉริยะ", "ZenWedge คือตัวจับเวลาถอยหลังที่หรูหรา ออกแบบมาเพื่อการจดจ่อที่ลึกซึ้ง\n\nคุณสมบัติ:\n• การปรับเวลาสัมผัส: เลื่อนตัวเลขเพื่อตั้งค่าเซสชันของคุณ\n• เสียงบำบัด: ชามร้องเพลงและระฆังเซน\n• คำแนะนำ AI: ให้ AI แนะนำเสียงที่เหมาะสมที่สุด\n• การวิเคราะห์: ติดตามแนวโน้มความสนใจของคุณ\n\nเริ่มจดจ่อตั้งแต่วันนี้กับ ZenWedge"),
    ("tr", "ZenWedge: Odak Sayacı", "Dokunmatik kontroller, rahatlatıcı sesler ve yapay zeka ile odaklanma sayacı.", "ZenWedge, derin odaklanma geliştirmenize yardımcı olmak için tasarlanmış zarif bir sayaçtır.\n\nÖzellikler:\n• Dokunmatik Zaman Ayarı: Seanslarınızı yapılandırmak için kaydırın.\n• Terapötik Sesler: Otantik Tibet kaseleri ve zen zilleri.\n• AI Önerileri: Gemini'nin en iyi sesi önermesine izin verin.\n• Analizler: Dikkat eğilimlerinizi izleyin.\n\nZenWedge ile bugün odaklanmaya başlayın."),
    ("uk", "ZenWedge: Таймер Фокусу", "Сенсорний таймер з тактильним керуванням, звуками та штучним інтелектом", "ZenWedge — це елегантний таймер зворотного відліку, розроблений для глибокого зосередження.\n\nОсобливості:\n• Тактильне налаштування: посуньте клин, щоб налаштувати сеанс.\n• Терапевтичні звуки: автентичні співаючі чаші та дзен-дзвоники.\n• Рекомендації ШІ: дозвольте Gemini порекомендувати оптимальний звук.\n• Аналітика: стежте за тенденціями вашої уваги.\n\nПочніть зосереджуватися вже сьогодні з ZenWedge."),
    ("vi", "ZenWedge: Hẹn giờ", "Hẹn giờ đếm ngược trực quan với âm thanh thiền định, AI thông minh & thống kê.", "ZenWedge là ứng dụng đếm ngược tập trung tinh tế, giàu trải nghiệm giác quan, giúp bạn rèn luyện sự tập trung sâu sắc.\n\nTính năng:\n• Điều chỉnh thời gian vật lý: Kéo trượt hình nêm mượt mà để tùy chỉnh phiên tập trung.\n• Âm thanh thư thái: Chuông Tây Tạng, hạt mưa và chuông thiền.\n• Đề xuất AI: Trợ lý Gemini phân tích lịch sử để đề xuất âm thanh tối ưu.\n• Phân tích & Thống kê: Theo dõi xu hướng tập trung của bạn.\n\nBắt đầu tập trung ngay hôm nay cùng ZenWedge."),
    ("zh-rCN", "ZenWedge: 专注计时器", "带有触觉控制、环境音效和AI智能推荐的沉浸式专注倒计时器。", "ZenWedge 是一款优雅且充满感官体验的倒计时器，旨在帮助您培养深度的专注力。\n\n特点：\n• 触觉时间调整：滑动机械楔子以配置您的专注会话。\n• 治愈音效：正宗的颂钵、雨滴和禅宗钟声。\n• AI 推荐：让 Gemini 分析您的历史记录以推荐最佳音效。\n• 分析：通过本地图表监控您的注意力趋势。\n\n今天就与 ZenWedge 一起开始专注吧。")
]

with open('/app/store_listing.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['Locale', 'App Name (<=30)', 'Short Description (<=80)', 'Full Description (<=4000)'])
    for row in data:
        writer.writerow(row)
